version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: medibridge-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: medibridge
      POSTGRES_USER: medibridge
      POSTGRES_PASSWORD: medibridge

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: